#!/bin/sh
# Compare reference CRIU images with images generated by the A3 module.
# This is a strict development diagnostic; the restore gate is cross-restore.sh.
set -eu

ROOT=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
CRIU=${CRIU:-}
CRIT=${CRIT:-}
MODULE=${MODULE:-$ROOT/kernel_module/criu_kernel.ko}
CONVERTER=${CONVERTER:-$ROOT/userspace/criu-module-convert/criu-module-convert}
DEBUG_ROOT=${DEBUG_ROOT:-/sys/kernel/debug}
DEBUG_DIR=$DEBUG_ROOT/criu

skip()
{
	echo "A3_FIELD_COMPARE: SKIP: $*" >&2
	exit 77
}

fail()
{
	echo "A3_FIELD_COMPARE: FAIL: $*" >&2
	exit 1
}

[ "$(id -u)" = 0 ] || skip "must run as root in the guest"
[ -f "$MODULE" ] || skip "module not found: $MODULE"
[ -x "$CONVERTER" ] || {
	make -C "$ROOT/userspace/criu-module-convert" clean all >/dev/null 2>&1 ||
		fail "cannot build $CONVERTER"
}
[ -x "$ROOT/tests/progs/minimal" ] ||
	make -C "$ROOT/tests/progs" minimal >/dev/null 2>&1 ||
	fail "cannot build minimal test program"

if [ -z "$CRIU" ]; then
	CRIU=$(command -v criu 2>/dev/null || true)
	[ -n "$CRIU" ] || [ -x "$ROOT/criu/criu/criu" ] ||
		skip "criu binary is unavailable"
	[ -n "$CRIU" ] || CRIU=$ROOT/criu/criu/criu
fi

crit_decode()
{
	image=$1
	output=$2
	if [ -n "$CRIT" ]; then
		"$CRIT" decode -i "$image" --pretty >"$output"
	elif command -v crit >/dev/null 2>&1; then
		crit decode -i "$image" --pretty >"$output"
	elif [ -f "$ROOT/criu/crit/crit/__main__.py" ]; then
		PYTHONPATH="$ROOT/criu/lib:$ROOT/criu/crit" \
			python3 -m crit decode -i "$image" --pretty >"$output"
	else
		return 127
	fi
}

if ! mountpoint -q "$DEBUG_ROOT" 2>/dev/null; then
	mount -t debugfs none "$DEBUG_ROOT" 2>/dev/null ||
		skip "cannot mount debugfs at $DEBUG_ROOT"
fi

TMP=$(mktemp -d "${TMPDIR:-/tmp}/a3-field-compare.XXXXXX")
REF=$TMP/reference
OURS=$TMP/module
mkdir -p "$REF" "$OURS"
TARGET_OUT=$TMP/target.out
TARGET_ERR=$TMP/target.err
INPUT=$TMP/stdin
: >"$INPUT"
PID=0
MODULE_LOADED=0
cleanup()
{
	if [ "$PID" -gt 0 ] 2>/dev/null; then
		kill -9 "$PID" 2>/dev/null || true
		wait "$PID" 2>/dev/null || true
	fi
	if [ "$MODULE_LOADED" = 1 ]; then
		rmmod criu_kernel 2>/dev/null || true
	fi
	rm -rf "$TMP"
}
trap cleanup EXIT HUP INT TERM

# Launch from / with all standard descriptors backed by regular files.
(cd / && exec "$ROOT/tests/progs/minimal" <"$INPUT" >"$TARGET_OUT" 2>"$TARGET_ERR") &
PID=$!
for _ in $(seq 1 100); do
	if grep -q '^pid=' "$TARGET_OUT" 2>/dev/null; then
		break
	fi
	sleep 0.05
done
grep -q '^pid=' "$TARGET_OUT" || fail "minimal did not start (see $TARGET_ERR)"

"$CRIU" dump -t "$PID" -D "$REF" --leave-running --shell-job \
	-v4 --log-file="$TMP/reference.log" || {
	tail -80 "$TMP/reference.log" >&2 2>/dev/null || true
	fail "reference criu dump failed"
}

insmod "$MODULE" || fail "insmod failed"
MODULE_LOADED=1
[ -e "$DEBUG_DIR/target" ] && [ -e "$DEBUG_DIR/dump" ] ||
	fail "module dump controls are unavailable"
printf '%s\n' "$PID" >"$DEBUG_DIR/target" || fail "selecting target failed"
printf '%s %s\n' "$PID" "$TMP/snapshot.bin" >"$DEBUG_DIR/dump" ||
	fail "module dump failed"
rmmod criu_kernel || fail "rmmod failed"
MODULE_LOADED=0
"$CONVERTER" "$TMP/snapshot.bin" -D "$OURS" || fail "snapshot conversion failed"

IMAGES="inventory.img pstree.img core-$PID.img mm-$PID.img pagemap-$PID.img files.img fdinfo-1.img fs-$PID.img creds-$PID.img reg-files.img"
DIFF=0
for image in $IMAGES; do
	ref_image=$REF/$image
	our_image=$OURS/$image
	if [ ! -f "$ref_image" ]; then
		# reg-files.img is a legacy compatibility image and is absent from
		# current CRIU dumps, which place reg_file_entry inside files.img.
		[ "$image" = reg-files.img ] && continue
		echo "A3_FIELD_COMPARE: reference image missing: $image" >&2
		DIFF=1
		continue
	fi
	if [ ! -f "$our_image" ]; then
		echo "A3_FIELD_COMPARE: module image missing: $image" >&2
		DIFF=1
		continue
	fi
	ref_json=$TMP/ref-$image.json
	our_json=$TMP/ours-$image.json
	if ! crit_decode "$ref_image" "$ref_json"; then
		echo "A3_FIELD_COMPARE: crit cannot decode reference $image" >&2
		DIFF=1
		continue
	fi
	if ! crit_decode "$our_image" "$our_json"; then
		echo "A3_FIELD_COMPARE: crit cannot decode module $image" >&2
		DIFF=1
		continue
	fi
	for side in ref ours; do
		json=$ref_json
		[ "$side" = ours ] && json=$our_json
		out=$TMP/$side-$image.norm
		python3 - "$json" "$out" <<'PY'
import json
import sys

# These are generated by CRIU per invocation and have no restore semantics.
ALLOW = {"dump_uptime", "dump_criu_run_id"}

def normalize(value):
    if isinstance(value, dict):
        return {key: normalize(item) for key, item in sorted(value.items())
                if key not in ALLOW}
    if isinstance(value, list):
        return [normalize(item) for item in value]
    return value

with open(sys.argv[1], encoding="utf-8") as source:
    value = normalize(json.load(source))
with open(sys.argv[2], "w", encoding="utf-8") as dest:
    json.dump(value, dest, indent=2, sort_keys=True)
    dest.write("\n")
PY
	done
	if ! diff -u "$TMP/ref-$image.norm" "$TMP/ours-$image.norm" >"$TMP/$image.diff"; then
		echo "A3_FIELD_COMPARE: unexpected differences in $image" >&2
		sed -n '1,160p' "$TMP/$image.diff" >&2
		DIFF=1
	fi
done

[ "$DIFF" -eq 0 ] || fail "field comparison found differences"
echo "A3_FIELD_COMPARE: PASS"
